# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

services:
  node-exporter:
    image: prom/node-exporter:v1.5.0
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    ports:
      - published: 9100
        target: 9100
        mode: host
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        io.prometheus.enabled: "true"
        io.prometheus.job_name: "node-exporter"
        io.prometheus.scrape_port: "9100"
        io.prometheus.metrics_path: "/metrics"
        io.prometheus.internal: "true"
    volumes:
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /proc
        target: /host/proc
        read_only: true
      - type: bind
        source: /sys
        target: /host/sys
        read_only: true
    hostname: "{{.Node.ID}}.node-exporter.svc.dockerswarm.internal"
    networks:
      - dockerswarm_monitor

networks:
  dockerswarm_monitor:
    name: dockerswarm_monitor
    external: true
