# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    command: -logtostderr -docker_only
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        io.prometheus.enabled: "true"
        io.prometheus.job_name: "cadvisor"
        io.prometheus.scrape_port: "8080"
        io.prometheus.metrics_path: "/metrics"
        io.prometheus.internal: "true"
    ports:
      - published: 8080
        target: 8080
        mode: host
    hostname: cadvisor.svc.dockerswarm.internal
    volumes:
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /var/run
        target: /var/run
        read_only: true
      - type: bind
        source: /sys
        target: /sys
        read_only: true
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      # - type: bind
      #   source: /dev/disk
      #   target: /dev/disk
      #   read_only: true
      # - type: bind
      #   source: /dev/kmsg
      #   target: /dev/kmsg
      #   read_only: true
    networks:
      - dockerswarm_monitor

networks:
  dockerswarm_monitor:
    name: dockerswarm_monitor
    external: true
