scrape_configs:
  # Create a job for Docker daemons.
  - job_name: 'dockerswarm_nodes'

    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes

    relabel_configs:
      # ================================================================================
      # Override prometheus internal labels
      # ================================================================================
      - source_labels:
        - __meta_dockerswarm_node_address
        target_label: __address__
        replacement: $1:9323

      # Set hostname as instance label
      - source_labels:
        - __meta_dockerswarm_node_address
        target_label: instance

      # ================================================================================
      # Label mapping
      # ================================================================================
      - action: labelmap
        regex: __meta_(dockerswarm_node_.+)
