scrape_configs:

  - job_name: 'dockerswarm-blackbox-exporter'

    static_configs:
      - targets: ['blackbox-exporter.svc.dockerswarm.internal:9115']

  - job_name: 'dockerswarm-services'

    metrics_path: /probe
    params:
      module: [http_2xx]

    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: services

    relabel_configs:
      # ================================================================================
      # Keep or drop targets with the following rules
      # ================================================================================

      # io.prometheus.probe_enabled=<true|false>
      # - source_labels:
      #   - __meta_dockerswarm_service_label_io_prometheus_probe_enabled
      #   regex: 'true'
      #   action: keep

      # Drop services with the following labels
      # - io.prometheus.internal=<true|false>
      - source_labels:
        - __meta_dockerswarm_service_label_io_prometheus_internal
        regex: 'true'
        action: drop

      # Keep only tasks connected to the Docker Swarm's Ingress network
      - source_labels:
        - __meta_dockerswarm_network_name
        regex: (^dockerswarm_monitor$)
        action: keep

      # ================================================================================
      # Override prometheus and blackbox internal labels
      # ================================================================================
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox-exporter.svc.dockerswarm.internal:9115
      - source_labels: [__param_target]
        target_label: instance
      
      # ================================================================================
      # Kubernetes compatible relabeling
      # - namespace
      # - deployment
      # - pod
      # ================================================================================
      # Set Kubernetes's Namespace with "com.docker.stack.namespace" label
      - source_labels:
        - __meta_dockerswarm_service_label_com_docker_stack_namespace
        target_label: namespace

      # Set Kubernetes's Deployment with "com.docker.stack.namespace" label
      - source_labels:
        - __meta_dockerswarm_service_label_com_docker_stack_namespace
        target_label: deployment

      # Set Kubernetes' Service Name with Docker Swarm's Service Name
      - source_labels:
        - __meta_dockerswarm_service_name
        target_label: service
        separator: '.'

      # Set Kubernetes's Pod Name with Docker Swarm's Service Name
      - source_labels:
        - __meta_dockerswarm_service_name
        target_label: pod
        separator: '.'
